disabled_rules: # rule identifiers to exclude from running
  - nesting
  - orphaned_doc_comment
  - superfluous_disable_command
# parameterized rules are first parameterized as a warning level, then error level.
line_length:
    warning: 200
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 80
    error: 100
type_body_length:
    warning: 400
    error: 500
cyclomatic_complexity:
    warning: 20
    error: 20
# paths to ignore
identifier_name:
  excluded:
    - id 
included:  
  - Sources
  - Example
excluded:
  - Pods
  - Carthage
  - vendor
  - .build     
  - Sources/Classes/core/JavascriptBridge
